#!/usr/bin/env python

import argparse

from pymmpz import get_xml


def main():
    parser = argparse.ArgumentParser(description="Convert MMPZ to XML")
    parser.add_argument("filename", help="Name of MMPZ file to read")
    args = parser.parse_args()

    print get_xml(args.filename)


if __name__ == "__main__":
    main()
