#!/usr/bin/env python

import argparse

from pymmpz import convert_mmpz_to_midi


def main():
    parser = argparse.ArgumentParser(description="Convert MMPZ to MIDI")
    parser.add_argument(
        "infile", metavar="FILENAME", help="Name of MMPZ file to read"
    )
    parser.add_argument(
        "outfile", metavar="FILENAME", help="Name of MIDI file to write"
    )
    args = parser.parse_args()

    convert_mmpz_to_midi(args.infile, args.outfile)


if __name__ == "__main__":
    main()
